### ISSUE TITLE
Improve ported implementation

### ISSUE THREAD

**Issue by MaxGraey** [kyranet/levenshtein-wasm#10]
I guess this wasm version is port of levenshtein-js. Wdyt about port [fast-levenshtein](https://github.com/hiddentao/fast-levenshtein) instead? It looks like much simpler and faster and don't require store full matrix.

**Comment by kyranet** [comment]
It still uses arrays, though fast-levenshtein re-uses them:

https://github.com/hiddentao/fast-levenshtein/blob/9c3c4aa3e19f8faf36b2d5df9884532563332094/levenshtein.js#L11-L12

Also the benchmarks show it's slower:

**`leven` benchmarks**:

```
         165,926 op/s » leven
         164,398 op/s » talisman
           1,044 op/s » levenshtein-edit-distance
             628 op/s » fast-levenshtein
             497 op/s » levenshtein-component
             195 op/s » ld
             190 op/s » levenshtein
             168 op/s » levdist
              10 op/s » natural
``` 

**`fast-levenshtein` benchmarks**:

```
Running suite Implementation comparison [benchmark/speed.js]...
>> levenshtein-edit-distance x 234 ops/sec ±3.02% (73 runs sampled)
>> levenshtein-component x 422 ops/sec ±4.38% (83 runs sampled)
>> levenshtein-deltas x 283 ops/sec ±3.83% (78 runs sampled)
>> natural x 255 ops/sec ±0.76% (88 runs sampled)
>> levenshtein x 180 ops/sec ±3.55% (86 runs sampled)
>> fast-levenshtein x 1,792 ops/sec ±2.72% (95 runs sampled)
Benchmark done.
Fastest test is fast-levenshtein at 4.2x faster than levenshtein-component
```

**`js-levenshtein` benchmarks**:

```
                      50 paragraphs, length max=500 min=240 avr=372.5
             162 op/s » js-levenshtein
              98 op/s » talisman
              94 op/s » levenshtein-edit-distance
              85 op/s » leven
              39 op/s » fast-levenshtein

                      100 sentences, length max=170 min=6 avr=57.5
           3,076 op/s » js-levenshtein
           2,024 op/s » talisman
           1,817 op/s » levenshtein-edit-distance
           1,633 op/s » leven
             800 op/s » fast-levenshtein

                      2000 words, length max=20 min=3 avr=9.5
           3,119 op/s » js-levenshtein
           2,416 op/s » talisman
           2,141 op/s » levenshtein-edit-distance
           1,855 op/s » leven
           1,260 op/s » fast-levenshtein
```

I'm not sure why each benchmark's results differ, and why some do so much, I have yet to benchmark all of them together. @vladfrangu has been working on benchmarks for this module, those are the initial results (before rewriting to Leven's implementation):

```
levenshtein-wasm x 710 ops/sec ±6.04% (70 runs sampled)
js-levenshtein x 1,498 ops/sec ±0.38% (89 runs sampled)
talisman x 1,484 ops/sec ±0.85% (92 runs sampled)
levenshtein-edit-distance x 1,281 ops/sec ±0.16% (93 runs sampled)
leven x 1,360 ops/sec ±0.14% (93 runs sampled)
fast-levenshtein x 1,008 ops/sec ±0.44% (91 runs sampled)
Fastest is js-levenshtein

Running paragraph
levenshtein-wasm x 49.98 ops/sec ±0.06% (63 runs sampled)
js-levenshtein x 80.81 ops/sec ±3.30% (68 runs sampled)
talisman x 52.76 ops/sec ±5.84% (66 runs sampled)
levenshtein-edit-distance x 46.37 ops/sec ±3.16% (59 runs sampled)
leven x 51.51 ops/sec ±3.20% (63 runs sampled)
fast-levenshtein x 29.58 ops/sec ±2.66% (51 runs sampled)
Fastest is js-levenshtein

Running Sentence
levenshtein-wasm x 865 ops/sec ±1.96% (82 runs sampled)
js-levenshtein x 1,446 ops/sec ±2.64% (87 runs sampled)
talisman x 1,027 ops/sec ±4.12% (82 runs sampled)
levenshtein-edit-distance x 906 ops/sec ±3.03% (88 runs sampled)
leven x 1,042 ops/sec ±2.22% (89 runs sampled)
fast-levenshtein x 632 ops/sec ±1.19% (89 runs sampled)
Fastest is js-levenshtein
```

And in another benchmark suite:

![image](https://user-images.githubusercontent.com/24852502/58916460-0bea7d00-8724-11e9-8fc5-a3996f9aa789.png)

Consistently, `js-levenshtein` ends up being the fastest in three benchmark suites, I don't know why the benchmarks mark the library they're on as the fastest, I guess I'll put a graph like [deno](https://denoland.github.io/deno/benchmarks.html#req-per-sec) does, while warming up the code before actually benchmarking this, and running them in separate threads (Web Workers? Child processes?) so the HEAP of one benchmark doesn't affect the others (I noticed in Node.js 6 that in any benchmark, the first function runs faster than if it were the second or the third), thus unmasking the true performance behind them. Thoughts? 

---

I think I will wait for #2 to be finished and ready before we can make assumptions about what's faster, specially since one of Wasm's strongest points is predictable performance, and some benchmark suites don't warm V8 to fire up TurboFan, optimize the code, and make a correct performance comparison.

**Comment by vladfrangu** [comment]
I have finished my benchmarking PR, #2, which adds the benchmarks to the Azure Pipelines, and while everything does work, we are missing the function that allows us to remove the allocated strings from memory.. Due to that, we cannot benchmark this "properly" yet.

<hr>

The stacktrace for the error is as follows: 

```
yarn run v1.13.0
$ node benchmark/benchmark
Running Word
wasm-10b093f2:1



RuntimeError: memory access out of bounds
    at wasm-function[3]:173
    at Object.wrap [as levenshtein] (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\dist\loader.js:157:16)
    at levenshtein (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\dist\index.js:12:23)
    at wordBench (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\benchmark\benchmark.js:1172:9)
    at Benchmark.<anonymous> (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\benchmark\benchmark.js:1188:36)
    at Benchmark.eval [as compiled] (eval at createCompiled (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\benchmark\node_modules\benchmark\benchmark.js:1725:16), <anonymous>:5:124)
    at clock (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\benchmark\node_modules\benchmark\benchmark.js:1658:29)
    at cycle (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\benchmark\node_modules\benchmark\benchmark.js:2007:49)
    at C:\Users\Vlad\Desktop\Development\levenshtein-wasm\benchmark\node_modules\benchmark\benchmark.js:2061:37
    at Timeout._onTimeout (C:\Users\Vlad\Desktop\Development\levenshtein-wasm\benchmark\node_modules\lodash\lodash.js:2756:43)
```

If it's an error in the current code, please let us know or leave a PR, I'm sure @kyranet wouldn't mind! After this is fixed (and no other errors creep up), we can give this a proper benchmark. 👍

**Comment by kyranet** [comment]
[CI](https://dev.azure.com/kyranet/kyranet.public/_build/results?buildId=2614&view=logs&jobId=9ef21fd1-5d60-5fa4-f8b2-6dc79e173863&taskId=516d74c5-15a9-50a0-24d9-dba41a487a2d&lineStart=21&lineEnd=39&colStart=1&colEnd=1) on benchmark.

**Comment by MaxGraey** [comment]
Yeah, it seems `leven` and `js-levenshtein` should be faster. Ok, did you think about approximations like [ukkonen](https://github.com/sunesimonsen/ukkonen)?

@vladfrangu This strange. But I recommend use `buddy` allocator currently. `tlsf` in master have some bugs which already fixed in `dev` branch

**Comment by kyranet** [comment]
Uhm, not a fan of [multiple memory allocations](https://github.com/sunesimonsen/ukkonen/blob/1a46b9fc74cacf9bac32d0a454b2c69b30811549/index.js#L57-L66), that approach is very complex and could be documented more. But I'm up to porting it if it's the fastest approach, I didn't know about that one!

Also I think the memory issue @vladfrangu is reporting is related to this:

https://github.com/kyranet/levenshtein-wasm/blob/90d54dfe369f6c3e61ea2ac62e9088f60291d083/src/index.ts#L13

As it's creating new strings into the Wasm memory, but never freeing them, unless I'm missing something 😅

**Comment by kyranet** [comment]
By the way, does AssemblyScript give any mechanism to create a value array (without pointers to memory)? I think dropping memory allocation, deallocation, and accesses, would allow further optimizations, speeding up operations substantially.

**Comment by MaxGraey** [comment]
> As it's creating new strings into the Wasm memory, but never freeing them, unless I'm missing something

Yes, if you alloc new string on js side you should free it.

@kyranet You could work with raw linear memory directly. Like in game-of-life example

**Comment by kyranet** [comment]
> Yes, if you alloc new string on js side you should free it.

That's what I want to do, the new docs show uses of `module.__retain`, `module.__allocString`, and `module.__release` in the [loader basics](https://docs.assemblyscript.org/basics/loader):

```typescript
var str = myModule.__retain(myModule.__allocString("my string"));
var foo = new myModule.Foo(str);
// do something with foo
myModule.__release(foo);
myModule.__release(str);
```

But those are for the `dev` branch, [`__allocString`](https://github.com/AssemblyScript/assemblyscript/blob/3229b71d911c62d17d65b47b68d26481904bddf3/lib/loader/index.js#L134-L142) is defined and maybe [`__retain`](https://github.com/AssemblyScript/assemblyscript/blob/3229b71d911c62d17d65b47b68d26481904bddf3/lib/loader/index.js#L87) too, but I don't see any occurrence of `__release`. And I don't know about the master branch, which this module uses.

> You could work with raw linear memory directly. Like in game-of-life example

Checked it, it uses `load`/`store`, which I already use, is this the right approach? For somebody who has worked with ARM a little, those names sound like they operate with the RAM memory/HEAP, which I want to avoid.

**Comment by MaxGraey** [comment]
> Checked it, it uses load/store, which I already use, is this the right approach? For somebody who has worked with ARM a little, those names sound like they operate with the RAM memory/HEAP, which I want to avoid.

You can't avoid this especially when working with strings. Wasm hasn't shadow stack, only locals & globals and linear memory (heap)

**Comment by kyranet** [comment]
@vladfrangu's benchmark PR got merged! The reports from Azure Pipelines:

```javascript
$ node benchmark/benchmark
Running Word
levenshtein-wasm x 473 ops/sec ±1.01% (86 runs sampled)
js-levenshtein x 2,176 ops/sec ±0.92% (89 runs sampled)
talisman x 1,846 ops/sec ±1.00% (91 runs sampled)
levenshtein-edit-distance x 1,567 ops/sec ±1.23% (89 runs sampled)
leven x 1,532 ops/sec ±1.10% (89 runs sampled)
fast-levenshtein x 1,307 ops/sec ±1.02% (89 runs sampled)
Fastest is js-levenshtein

Running paragraph
levenshtein-wasm x 21.20 ops/sec ±1.56% (39 runs sampled)
js-levenshtein x 104 ops/sec ±0.96% (74 runs sampled)
talisman x 68.87 ops/sec ±1.07% (69 runs sampled)
levenshtein-edit-distance x 59.59 ops/sec ±1.24% (61 runs sampled)
leven x 60.67 ops/sec ±0.86% (62 runs sampled)
fast-levenshtein x 41.88 ops/sec ±1.67% (55 runs sampled)
Fastest is js-levenshtein

Running Sentence
levenshtein-wasm x 435 ops/sec ±0.85% (89 runs sampled)
js-levenshtein x 1,932 ops/sec ±1.01% (91 runs sampled)
talisman x 1,445 ops/sec ±0.79% (92 runs sampled)
levenshtein-edit-distance x 1,139 ops/sec ±1.20% (88 runs sampled)
leven x 1,157 ops/sec ±1.07% (90 runs sampled)
fast-levenshtein x 856 ops/sec ±1.12% (87 runs sampled)
Fastest is js-levenshtein
Done in 116.09s.
```

The newest master has the latest code from AssemblyScript, I also noticed the output code grew up a lot (from around ~450 lines to ~2600 lines), however, this `__retains` the string and `__releases` it, so there are no memory issues anymore.

**Comment by kyranet** [comment]
This is curious, I tried removing extra code from the JS side code, but no luck speeding it up:

```diff
diff --git a/src/index.ts b/src/index.ts
index 9021e15..32fb022 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -11,12 +11,7 @@ export function levenshtein(a: string, b: string): number {
 	if (a === b) return 0;
 	if (a.length > b.length) [a, b] = [b, a];
 
-	const ptrB = wasmModule.__retain(wasmModule.__allocString(b));
-	const ptrA = wasmModule.__retain(wasmModule.__allocString(a));
-	try {
-		return wasmModule.levenshtein(ptrA, ptrB);
-	} finally {
-		wasmModule.__release(ptrA);
-		wasmModule.__release(ptrB);
-	}
+	const ptrB = wasmModule.__allocString(b);
+	const ptrA = wasmModule.__allocString(a);
+	return wasmModule.levenshtein(ptrA, ptrB);
 }
```

<details>
  <summary>Before</summary>
<pre>
Running Word
levenshtein-wasm x 443 ops/sec ±0.52% (90 runs sampled)
js-levenshtein x 1,799 ops/sec ±0.80% (93 runs sampled)
talisman x 1,674 ops/sec ±1.77% (90 runs sampled)
levenshtein-edit-distance x 1,502 ops/sec ±0.39% (94 runs sampled)
leven x 1,541 ops/sec ±0.34% (95 runs sampled)
fast-levenshtein x 1,185 ops/sec ±0.71% (93 runs sampled)
Fastest is js-levenshtein
</pre>
<pre>
Running paragraph
levenshtein-wasm x 18.70 ops/sec ±1.03% (49 runs sampled)
js-levenshtein x 87.16 ops/sec ±1.24% (73 runs sampled)
talisman x 60.22 ops/sec ±1.37% (62 runs sampled)
levenshtein-edit-distance x 56.00 ops/sec ±0.48% (71 runs sampled)
leven x 57.13 ops/sec ±0.75% (72 runs sampled)
fast-levenshtein x 34.97 ops/sec ±0.69% (60 runs sampled)
Fastest is js-levenshtein
</pre>
<pre>
Running Sentence
levenshtein-wasm x 385 ops/sec ±0.52% (90 runs sampled)
js-levenshtein x 1,599 ops/sec ±0.57% (92 runs sampled)
talisman x 1,256 ops/sec ±0.56% (92 runs sampled)
levenshtein-edit-distance x 1,120 ops/sec ±1.03% (93 runs sampled)
leven x 1,162 ops/sec ±0.48% (93 runs sampled)
fast-levenshtein x 718 ops/sec ±0.48% (92 runs sampled)
Fastest is js-levenshtein
Done in 119.82s.
</pre>
</details>

<details>
  <summary>After</summary>
<pre>
Running Word
levenshtein-wasm x 423 ops/sec ±3.64% (82 runs sampled)
js-levenshtein x 1,812 ops/sec ±0.74% (93 runs sampled)
talisman x 1,750 ops/sec ±0.34% (95 runs sampled)
levenshtein-edit-distance x 1,479 ops/sec ±0.60% (93 runs sampled)
leven x 1,530 ops/sec ±0.42% (94 runs sampled)
fast-levenshtein x 1,192 ops/sec ±0.34% (94 runs sampled)
Fastest is js-levenshtein
</pre>
<pre>
Running paragraph
levenshtein-wasm x 18.98 ops/sec ±0.46% (50 runs sampled)
js-levenshtein x 89.11 ops/sec ±0.41% (74 runs sampled)
talisman x 62.03 ops/sec ±0.22% (64 runs sampled)
levenshtein-edit-distance x 56.68 ops/sec ±1.15% (72 runs sampled)
leven x 57.90 ops/sec ±0.37% (73 runs sampled)
fast-levenshtein x 35.30 ops/sec ±0.46% (61 runs sampled)
Fastest is js-levenshtein
</pre>
<pre>
Running Sentence
levenshtein-wasm x 389 ops/sec ±0.39% (91 runs sampled)
js-levenshtein x 1,631 ops/sec ±0.43% (95 runs sampled)
talisman x 1,271 ops/sec ±0.35% (94 runs sampled)
levenshtein-edit-distance x 1,143 ops/sec ±0.28% (95 runs sampled)
leven x 1,173 ops/sec ±0.44% (94 runs sampled)
fast-levenshtein x 725 ops/sec ±0.39% (93 runs sampled)
Fastest is js-levenshtein
Done in 120.95s.
</pre>
</details>

**Comment by kyranet** [comment]
**Update**: I have ported `js-levenshtein`'s algorithm (since it's the fastest) in https://github.com/kyranet/levenshtein-wasm/commit/7c86572b182aafc1777fd70d76940577b3452f61, ukkonen measures Edit Distance and levenshtein... well... Levenshtein Distance. They are different algorithms with different usecases, the former is faster for long strings whereas the latter is faster for short strings, so I decided to stick with Levenshtein, maybe in the future, if this gets performant enough, I'll port Ukkonen as a separate library 👍 

<details>
  <summary>Benchmark Results</summary>
<pre>
Running Word
levenshtein-wasm x 623 ops/sec ±0.73% (92 runs sampled)
js-levenshtein x 1,815 ops/sec ±0.41% (93 runs sampled)
talisman x 1,666 ops/sec ±1.66% (90 runs sampled)
levenshtein-edit-distance x 1,441 ops/sec ±0.67% (88 runs sampled)
leven x 1,483 ops/sec ±0.63% (91 runs sampled)
fast-levenshtein x 1,055 ops/sec ±2.23% (83 runs sampled)
Fastest is js-levenshtein
</pre>
<pre>
Running paragraph
levenshtein-wasm x 34.44 ops/sec ±1.26% (59 runs sampled)
js-levenshtein x 72.18 ops/sec ±0.41% (72 runs sampled)
talisman x 56.72 ops/sec ±1.41% (60 runs sampled)
levenshtein-edit-distance x 55.15 ops/sec ±1.32% (70 runs sampled)
leven x 57.97 ops/sec ±0.33% (73 runs sampled)
fast-levenshtein x 35.40 ops/sec ±0.32% (61 runs sampled)
Fastest is js-levenshtein
</pre>
<pre>
Running Sentence
levenshtein-wasm x 779 ops/sec ±0.34% (93 runs sampled)
js-levenshtein x 1,630 ops/sec ±0.18% (95 runs sampled)
talisman x 1,274 ops/sec ±0.27% (95 runs sampled)
levenshtein-edit-distance x 1,141 ops/sec ±0.54% (94 runs sampled)
leven x 1,175 ops/sec ±0.27% (95 runs sampled)
fast-levenshtein x 726 ops/sec ±0.22% (93 runs sampled)
Fastest is js-levenshtein
Done in 120.07s.
</pre>
</details>
